### PR TITLE
#443 - employment, medical and ohs history

### LINKED ISSUE #443: Add employment history
I spoke with Kamila and she said that it will be very useful to add employment history. So each user should have something like: when he started job, what type of employment contract, when he finished job. History should also be displayed for users who are no longer active (dismissed). We can also add history of BHP and medical exams.

### PR DESCRIPTION
**Pull request by kamilpiech97**
Should close #443.
Added option for administrator to manage users `employment`, `medical exams` and `ohs trainings` history.
Added artisan `toby:move-user-data-to-history` command for migrate data about `ohs training` and `medical exam` into user history.
Added tests.

Preview:

[Screencast from 18-06-24 09:24:19.webm](https://github.com/blumilksoftware/toby/assets/29115024/8d502c1d-c84e-4831-9514-61eef00d171c)

### CODE REVIEW

**Comment by kamilpiech97** [comment]
> 1. Date format should be dd.mm.yyyy, we have now yyyy-mm-dd.
> 
> image
> 
> 2. Padding is too small - please look at other
> 
> image
> 
> Like here
> 
> image
> 
> 3. Please translate "type"
> 
> image
> 
> 4. We should add information that comment is optional.
> 5. Can we make like automatic history? I mean, when user has changes date of for example medical exams, can we add automatically entry to history?

1. FIxed but in #447, I added helper for that, I would use them here after merge.
2. Added
3. Added
4. Added
5. Removed that fields from user create/edit view after merge that PR, I should open PR with that #452

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. When I add information about employment form, but I don't fill date to, I see error:

image

Event if I fill date to, the error still occurs.

2. Please look at dates in other places in application - we have dots between numbers, not dashes.

History:

image

Requests:

image

3. Information about that comment is optional should look the same as in requests, like

image

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. When I add history about ohv and I don't fill date to, I see error

image


2. When I add information about employment, I can add employment form employment contract without date to, but in other cases I can't. Is it by purpose?

**Comment by kamilpiech97** [comment]
> 1. When I add history about ohv and I don't fill date to, I see error
> 
> image
> 
> 2. When I add information about employment, I can add employment form employment contract without date to, but in other cases I can't. Is it by purpose?

1. fixed
2. Yep, it's conditionally.

**Review by EwelinaSkrzypacz — COMMENTED** [review]
Why I see this? I believe that is for debugging and now it should be removed ;)

image

**Comment by kamilpiech97** [comment]
> Why I see this? I believe that was for debugging and now it should be removed ;)
> 
> image
> 
> EDIT:
> 
> Validation messages are not consistent
> 
> image

fixed :DDD

**Review by EwelinaSkrzypacz — APPROVED** [review]

**Review by Baakoma — APPROVED** [review]

**Pull request merged**
