### PR TITLE
#372 - spatie permissions update

### LINKED ISSUE #372: Update permissions package
I would like to update Spatie laravel-permissions from v5 to v6. Sadly, it's a lot of work, because there're many changes including conversino of ids to uuids, migrations changes etc.

* reference: https://spatie.be/docs/laravel-permission/v6/upgrading#content-upgrading-from-v5-to-v6

### PR DESCRIPTION
**Pull request by kamilpiech97**
Should close #372.
Updated migrations for properly running tests - in migrations updates are connected with getting variables when tables are creating.
Example, **before**:

`[$columnNames["team_foreign_key"], PermissionRegistrar::$pivotPermission, $columnNames["model_morph_key"], "model_type"],`

**after**:

`[$columnNames["team_foreign_key"], $pivotPermission, $columnNames["model_morph_key"], "model_type"],
`

and  `$pivotPermission` is retrieved on the top of migration file, like that: 
`$pivotPermission = $columnNames["permission_pivot_key"] ?? "permission_id";`

Also, we can stay with normal `ids` in permissions, we do not need to change them into `uuid`.

### CODE REVIEW

**Review by krzysztofrewak — COMMENTED** [review]
Okaaay, but what about production environment? We won't run these migrations there.

**Comment by EwelinaSkrzypacz** [comment]
> Okaaay, but what about production environment? We won't run these migrations there.

On beta environment it seems like it works without running migrations :eyes:

**Comment by kamilpiech97** [comment]
> > Okaaay, but what about production environment? We won't run these migrations there.
> 
> On beta environment it seems like it works without running migrations 👀

We do not need to run updated migrations because they do not change the database, only the logic of creating tables, and we update them only for tests.

**Comment by kamilpiech97** [comment]
> We do not need to run updated migrations because they do not change the database, only the logic of creating tables, and we update them only for tests.

We do not need to run updated migrations because they do not change the database, only the logic of creating tables, and we update them only for tests.

**Review by krzysztofrewak — APPROVED** [review]

**Review by EwelinaSkrzypacz — APPROVED** [review]

**Pull request merged**
