### PR TITLE
#115 - Adjust deployment

### PR DESCRIPTION
**Pull request by mtracz**
Added `git config --global --add safe.directory <PATH TO PROJECT>` for bot user which is used during deployment.

### CODE REVIEW

**Comment by mtracz** [comment]
test

**Comment by mtracz** [comment]
!deploy beta

**Comment by mtracz** [comment]
!deploy beta

**Comment by mtracz** [comment]
!deploy beta

**Comment by mtracz** [comment]
!deploy beta

**Comment by mtracz** [comment]
!deploy beta

**Comment by mtracz** [comment]
!deploy beta

**Comment by mtracz** [comment]
!deploy beta

**Review by EwelinaLasowy — APPROVED** [review]

**Pull request merged**
